[package]
name = "rustdb"
version = "0.1.37"
authors = ["George Barwood"]
edition = "2021"
description = "SQL database (in development)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/georgebarwood/RustDB/"
categories = ["database-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["max"]

# ````builtin``` exposes an interface that allows extra SQL builtin functions to be defined.
builtin = []

# ```max``` exposes a maximal interface, including internal modules.
max = ["builtin"]

[dependencies]
# stacker = "0.1"
# parking_lot = "0.11.2"
serde = { version = "1.0.130", features = ["derive","rc"] }

[dev-dependencies]
rand = "0.8.4"
mimalloc = { version = "0.1.26", default-features = false }
axum = { version = "0.4.0", default-features = false, features = ["multipart","http1"] }
#hyper = { version = "0.14.14", features = ["server"] }
tower = { version = "0.4.11" }
tower-cookies = "0.4.0"
tokio = { version = "1.14.0", features = ["full"] }
argon2rs = "0.2.5"
serde_json = "1.0.72"

#serde = { version = "1.0.130", features = ["derive"] }
#headers = "0.3.5"
#console-subscriber = { path = "../console-main/console-subscriber" }
#axum-debug = "0.2.0"

