[package]
name = "rustdb"
version = "1.0.4"
authors = ["George Barwood"]
edition = "2021"
description = "SQL database"
license = "MIT OR Apache-2.0"
repository = "https://github.com/georgebarwood/RustDB/"
categories = ["database-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["init","gentrans","max","pack","verify"]

# ```init``` : { init module ( SQL initialisation string )
init = []

# GenTransaction ( implementation of Transaction )
gentrans = []

# ````builtin``` : Allows extra SQL builtin functions to be defined.
builtin = []

# ```max``` : Full access, including direct access to database tables and all other internal modules.
max = ["builtin"]

# ```pack``` : Allows database pages to be packed using builtin function REPACKFILE.
pack = []

# ```verify``` : Allows database structure to be verified using builtin function VERIFYDB.
verify = []

[dependencies]
# stacker = "0.1"
# parking_lot = "0.11.2"
serde = { version = "1.0.131", features = ["derive","rc"] }
rustc-hash = "1.1.0"

[dev-dependencies]
rand = "0.8.4"
mimalloc = { version = "0.1.27", default-features = false }
axum = { version = "0.4.2", default-features = false, features = ["multipart","http1"] }
#hyper = { version = "0.14.14", features = ["server"] }
tower = { version = "0.4.11" }
tower-cookies = "0.4.0"
tokio = { version = "1.14.0", features = ["full"] }
argon2rs = "0.2.5"
serde_json = "1.0.72"

#serde = { version = "1.0.130", features = ["derive"] }
#headers = "0.3.5"
#console-subscriber = { path = "../console-main/console-subscriber" }
#axum-debug = "0.2.0"

